name: Link Check

on:
  pull_request:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Mondays at 06:00 UTC

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          # Check only the public README to avoid private build inputs
          args: >-
            --no-progress
            --verbose
            --max-redirects 10
            --timeout 20
            --exclude ^https://betterprogramming\.pub/how-to-write-a-web-app-in-rust-part-1-3047156660a7$
            --exclude ^https://blog\.gkomninos\.com/crafting-a-web-application-with-golang-a-step-by-step-guide$
            --exclude ^https://prasadtech\.hashnode\.dev/step-by-step-guide-to-building-an-amazon-clone-with-reactjs$
            --exclude ^https://www\.apptha\.com/blog/steps-to-build-a-private-one-to-one-chat-app/?$
            --exclude ^https://www\.reddit\.com/r/gamedev/comments/67frk2/tutorial_on_making_a_complete_game_with_lua_and/?$
            README.md
          format: markdown
          output: lychee/out.md
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
